"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import sys
from environs import Env

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# When frozen with PyInstaller, assets live under sys._MEIPASS (read-only temp),
# while writable dirs (media, staticfiles) should use current working directory.
if getattr(sys, "frozen", False):
    APP_DIR = Path(getattr(sys, "_MEIPASS", Path(__file__).resolve().parent.parent))
    RUNTIME_DIR = Path(os.getcwd())
else:
    APP_DIR = Path(__file__).resolve().parent.parent
    RUNTIME_DIR = APP_DIR

BASE_DIR = RUNTIME_DIR

env = Env()
env.read_env()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-#2#+yel1k9lkpeg5y)c^!o==wz)8z)bo1aj(yb@jnmhggn-z5i"
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    "192.168.0.198",
    "192.168.1.10",
    "*",
]


# Application definition

INSTALLED_APPS = [
    "daphne",
    "smartpark.apps.SmartparkConfig",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [APP_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"
ASGI_APPLICATION = "config.asgi.application"

USER_MODEL = "smartpark.CustomUser"

if DEBUG:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer",
        },
    }
else:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [
                    (env.str("REDIS_HOST", "127.0.0.1"), env.int("REDIS_PORT", 6379))
                ],
            },
        },
    }

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Database configuration
# Try PostgreSQL first, fallback to SQLite if not available
try:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": env.str("POSTGRES_DB", "smartautopark"),
            "USER": env.str("POSTGRES_USER", "postgres"),
            "PASSWORD": env.str("POSTGRES_PASSWORD", "admin"),
            "HOST": env.str("POSTGRES_HOST", "localhost"),
            "PORT": env.str("POSTGRES_PORT", "5432"),
        }
    }
except Exception:
    # Fallback to SQLite if psycopg2 is not available
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "uz-uz"

TIME_ZONE = "Asia/Tashkent"

USE_I18N = True
USE_TZ = False
USE_L10N = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

LOGOUT_REDIRECT_URL = "/login/"
LOGIN_REDIRECT_URL = "/home/"

STATIC_URL = "/static/"
STATIC_ROOT = RUNTIME_DIR / "staticfiles"
STATICFILES_DIRS = [
    APP_DIR / "static",
]
MEDIA_URL = "/media/"
MEDIA_ROOT = RUNTIME_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Increase upload limits for handling large multipart requests
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB

HOUR_PRICE = 4000
FREE_MINUTES = 10  # 10 daqiqa bepul

AUTH_USER_MODEL = "smartpark.CustomUser"
MIN_TIME_BETWEEN_ENTRIES = 2

# XPrinter USB sozlamalari
XPRINTER_VENDOR_ID = 0x1FC9  # XPrinter Vendor ID (VID)
XPRINTER_PRODUCT_ID = 0x2016  # XPrinter Product ID (PID)
XPRINTER_TIMEOUT = 1000  # USB timeout (ms)

# Printer configuration
PRINTER_NAME = env.str("PRINTER_NAME", None)


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "standard": {
            "format": "[%(asctime)s] [%(levelname)s] %(name)s: %(message)s",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
    },
    "handlers": {
        "sync_file": {
            "level": "INFO",
            "class": "logging.FileHandler",
            "filename": os.path.join(BASE_DIR, "logs", "sync.log"),
            "formatter": "standard",
        },
    },
    "loggers": {
        "unikassa_sync": {
            "handlers": ["sync_file"],
            "level": "INFO",
            "propagate": False,
        },
    },
}


LOG_DIR = os.path.join(BASE_DIR, "logs")

os.makedirs(LOG_DIR, exist_ok=True)
